### ISSUE TITLE
detect reverse proxy IP address

### ISSUE THREAD

**Issue by yitwail** [chrisguitarguy/simple-login-lockdown#7]
Chris,

Thanks for the plugin. It seems to work fine. I appreciate that it *only* locks down login and nothing else. For instance, Login Security Solution is nice but requires strong passwords, which not every user will accept.

Now, in the plugin description, you wrote, "If you're using a load balancer or in some other situation where you're behind a proxy, use this as an example and write your own." I did just that, instead of filtering the ip in functions.php, because I have a webserver with a lot of sites, and don't want to edit functions.php in each one.

So, here's what I changed. In login.php, I changed get_ip() to this:

    private function get_ip()
    {
        if (isset($_SERVER['HTTP_X_FORWARDED_FOR']))
            $ip = preg_replace('/^([^,]+).*$/', '\1', $_SERVER['HTTP_X_FORWARDED_FOR']);
        else
            $ip = isset($_SERVER['REMOTE_ADDR']) ? $_SERVER['REMOTE_ADDR'] : false;
        return apply_filters('simple_login_lockdown_ip', $ip);
    }

Any reason you couldn't alter the plugin to do this? If there's a X-Forwarded-For header, I can't think of why you shouldn't use that instead of REMOTE_ADDR. Or am I missing something? You could even make this an option, so it only does this if a checkbox for something like Reverse-proxy in use is checked.

regards,
John

**Comment by chrisguitarguy** [comment]
Closing this one out since the settings seems to have worked!
