### ISSUE TITLE
Spelling mistake / correction

### ISSUE THREAD

**Issue by neilmcg3000** [chrisguitarguy/simple-login-lockdown#8]
login.php

lines 168 & 169 - attemps - should be attempts

                __('Too many login attemps from one IP address! Please take a break and try again later', 'simple-login-lockdown'),
                __('Too many login attemps', 'simple-login-lockdown'),

Should read

                __('Too many login attempts from one IP address! Please take a break and try again later', 'simple-login-lockdown'),
                __('Too many login attempts', 'simple-login-lockdown'),

**Comment by chrisguitarguy** [comment]
Thanks @neilmcg3000 ! The changes in 1ec75d14ca4603d16a7d8f8827ef6621a9239012 removed those lines in favor of a `WP_Error` object that uses the correct spelling.
